publish:
    author_name: alexandra.leever@kaplan.com
    internal_reference: 1614836399901753270
    message: alexandra.leever@kaplan.com changed trunk/s9ml/chapter04/m001040.html
    metadata: None
    organizations: None
    project_id: 2cef0712-a267-4c93-8091-804d6630b802
    project_name: sn_5b53
    publishing_author: cda7988a-34ec-4afb-bdc0-2bf7d38a5e15
    publishing_status: draft
    reference: 20972
    tenant_id: ddd525b9-e47c-46ac-ab55-e0db93338ff3
content:
    active: true
    kaplan_type: question-set
    metadata: None
    recommended_time: None
    schema: 2.0
items:
    active: true
    default_value: None
    kaplan_type: question
    max_score: None
    metadata: None
    min_score: None
    recommended_time: None
    schema: 2.0
    kaplan_type: question
    max_score: None
    metadata: None
    min_score: None
    recommended_time: None
explanation:
    active: true
    kaplan_type: feedback
    metadata: None
    recommended_time: None
    schema: 2.0
    title: Explanation
interactions:
    active: true
    case_sensitive: false
    default_value: None
    display_type: single-response
    expected_length: None
    interaction_type: choice-interaction
    kaplan_type: interaction
    max_choices: 1
    max_length: None
    max_score: None
    metadata: None
    min_score: None
    recommended_time: None
    schema: 2.0
response_options:
    active: true
    kaplan_type: response-option
    metadata: None
    recommended_time: None
    schema: 2.0
    set: None
    value: None